### ISSUE TITLE
Separate declaration and defintion into multiple files.

### ISSUE THREAD

**Issue by PetorSFZ** [Gronis/OpenEcs#6]
While single-header libraries are very nice for quickly including into projects they also have one major problem (imo), they make it harder to read and understand the source. By splitting the code into a "normal" header file with just the declarations and a second header file with the implementation it will be easier to get a quick overview of what is available in the library without having to look through the implementation at the same time.

**Comment by Gronis** [comment]
I was thinking the same thing and started wondering if it is possible to generate a single header file from different separate files. Something like the library <a href="https://github.com/philsquared/Catch" >Catch</a> has done. However, keeping the single header format is (according to me) important, since users don't have to worry about linking libraries or installing dependencies beforehand, which can be quite annoying. Also most of the code needs to be in a header file anyway, since they are templated, so compiling anything beforehand is not necessary.

**Comment by PetorSFZ** [comment]
Well, since both the declaration and implementation will be in headers it should be just as simple to drop both files into the project. I basically mean that the "normal" header should #include<> the other header at the end.

**Comment by Gronis** [comment]
Wouldn't that be like adding all the implementation at the end of the header file?

**Comment by PetorSFZ** [comment]
Exactly. But the point is that you have separated it into different files.

**Comment by Gronis** [comment]
The implementation should be much more separated now (though it needs more work). Every file in the includes folder are used to generate a single header. Is this what you intended?

**Comment by PetorSFZ** [comment]
I haven't looked at it in detail (and probably won't tonight), but at first glance it looks a lot easier to grasp. The whole point is really to make it easier to understand the code, if you feel you've accomplished that, then yes. :)
